[site]: datascience
[post_id]: 89033
[parent_id]: 60738
[tags]: 
The output of a fit() method of a transformer is the class instance itself (it returns 'self'). Thus by doing: X_train=fill_values.fit(X_train) you destroyed the X_train dataFrame, and thus when you use it as input to transform() you get an error. Also, when calling fit() it prepares for the transform() so you should not call it again with other data, before calling transform() . You should instead do: from sklearn.impute import SimpleImputer fill_values=SimpleImputer(missing_values=0,strategy='mean') fill_values.fit(X_train) imp_X_train=fill_values.transform(X_train) fill_values.fit(X_test) imp_X_test=fill_values.trainsform(X_test)
