[site]: stackoverflow
[post_id]: 5339592
[parent_id]: 5335905
[tags]: 
Can you tell me what is happening when in celery you tell the task to retry? Will it retry in the same worker thread or it will be returned to broker which may send it elsewhere? Yes the task return to the broker (ex. Rabbit MQ) with a different estimated execution time What will happen with tasks for retry if worker or dispatcher suddenly stop? If tasks can be lost is there some approach to avoid this? May be save each task in database and retry them if no result is received for some time? Or may be dispatcher have it's own persistent storage? What about then if worker thread crash receiving the task or while executing it? Here a complete answer Retry Lost or Failed Tasks (Celery, Django and RabbitMQ)
