[site]: stackoverflow
[post_id]: 474930
[parent_id]: 474803
[tags]: 
If you are trying a complete network outage for your application unplugging the network cable will work. Sometimes you might have a data access layer with multiple data sources (on different machines) in which case you can simulate an exception in your tests with a Mock Framework like Rhino Mocks. Here is some pseudo-code that you may have in your test void TestUserDBFailure() { // ***** THIS IS PSEUDO-CODE ******* //setting up the stage - retrieval of the user info create an exception Expect.Call(_userRepository.GetUser(null)) .IgnoreArguments() .Return(new Exception()); // Call that uses the getuser function, see how it reacts User selectedUser = _dataLoader.GetUserData("testuser", "password"); }
